### ISSUE TITLE
license

### ISSUE THREAD

**Issue by aeosynth** [ichiKD/ichiKD.github.io#1]
hi, i noticed you took my code. it was unlicensed, but i've now added the mit license. could you please add that license file to this repo if you plan to keep using the code?

**Comment by ichiKD** [comment]
Ok, sure

**Comment by aeosynth** [comment]
sorry but i don't see the license added. what are you planning on doing?

**Comment by ichiKD** [comment]
@aeosynth 
I did now

**Comment by aeosynth** [comment]
cool, thanks
